luci-app-https-dns-proxy: Add he.net as provider
stangri/openwrt_packages pull request #142
Opened 2021-10-30 01:29 UTC by systemcrash

2021-11-01 15:33 UTC, stangri commented
Hey Paul,

this is just a placeholder for when I have the time to convert the lua app to javascript, it is not being built or used in any way right now.

If you want to add HE to the list of the providers in the current app, that would be `luci-app-https-dns-proxy` either in this repo or you can send a polished PR directly to github.com/openwrt/luci repo.

2021-11-01 15:34 UTC, stangri requested changes

2021-11-01 15:34 UTC, stangri commented on luci-app-https-dns-proxy-js/root/usr/share/https-dns-proxy/providers/net.he.ordns.json
> +	"label":_("HurricaneElectric"),
Please change to: `"label":_("Hurricane Electric"),`

2021-11-01 15:34 UTC, stangri commented on luci-app-https-dns-proxy/luasrc/https-dns-proxy/providers/net.he.ordns.lua
> +        label = _("HurricaneElectric"),
Please change to `label = _("Hurricane Electric"),`

2021-11-02 02:19 UTC, stangri approved these changes

2021-11-02 02:23 UTC, systemcrash commented
> If you want to add HE to the list of the providers in the current app, that would be `luci-app-https-dns-proxy` either in this repo or you can send a polished PR directly to github.com/openwrt/luci repo.

I'll try and get that squeezed in there...

2021-11-02 02:36 UTC, stangri commented
> > If you want to add HE to the list of the providers in the current app, that would be `luci-app-https-dns-proxy` either in this repo or you can send a polished PR directly to github.com/openwrt/luci repo.
> 
> I'll try and get that squeezed in there...

Shouldn't be hard, just squash all the commits into a single one or do 'git commit --amend' if you need to add more changes in the future.

2021-11-02 02:36 UTC, merged